use serde::Deserialize;
use time::OffsetDateTime;

#[derive(Debug, Deserialize)]
#[serde(tag = "event")]
pub enum Event {
    Fileheader,

    // [[Startup]]
    Cargo,
    ClearSavedGame,
    Commander,
    Loadout,
    Materials,
    Missions,
    NewCommander,
    LoadGame,
    Passengers,
    Powerplay,
    Progress,
    Rank,
    Reputation,
    Statistics,

    // [[Travel]]
    ApproachBody,
    Docked,
    DockingCancelled,
    DockingDenied,
    DockingGranted,
    DockingRequested,
    DockingTimeout,
    FSDJump,
    FSDTarget,
    LeaveBody,
    Liftoff,
    Location,
    StartJump,
    SupercruiseEntry,
    SupercruiseExit,
    Touchdown,
    Undocked,
    NavRoute,
    NavRouteClear,

    // [[Combat]]
    Bounty,
    CapShipBond,
    Died,
    EscapeInterdiction,
    FactionKillBond,
    FighterDestroyed,
    HeatDamage,
    HeatWarning,
    HullDamage,
    Interdicted,
    Interdiction,
    PVPKill,
    ShieldState,
    ShipTargeted,
    SRVDestroyed,
    UnderAttack,

    // [[Exploration]]
    CodexEntry,
    DiscoveryScan,
    Scan,
    FSSAllBodiesFound,
    FSSBodySignals,
    FSSDiscoveryScan,
    FSSSignalDiscovered,
    MaterialCollected,
    MaterialDiscarded,
    MaterialDiscovered,
    MultiSellExplorationData,
    NavBeaconScan,
    BuyExplorationData,
    SAAScanComplete,
    SAASignalsFound,
    ScanBaryCentre,
    SellExplorationData,
    Screenshot,

    // [[Trade]]
    AsteroidCracked,
    BuyTradeData,
    CollectCargo,
    EjectCargo,
    MarketBuy,
    MarketSell,
    MiningRefined,

    // [[Station Services]]
    BuyAmmo,
    BuyDrones,
    CargoDepot,
    CommunityGoal,
    CommunityGoalDiscard,
    CommunityGoalJoin,
    CommunityGoalReward,
    CrewAssign,
    CrewFire,
    CrewHire,
    EngineerApply,
    EngineerContribution,
    EngineerCraft,
    EngineerLegacyConvert,
    EngineerProgress,
    FetchRemoteModule,
    Market,
    MassModuleStore,
    MaterialTrade,
    MissionAbandoned,
    MissionAccepted,
    MissionCompleted,
    MissionFailed,
    MissionRedirected,
    ModuleBuy,
    ModuleRetrieve,
    ModuleSell,
    ModuleSellRemote,
    ModuleStore,
    ModuleSwap,
    Outfitting,
    PayBounties,
    PayFines,
    PayLegacyFines,
    RedeemVoucher,
    RefuelAll,
    RefuelPartial,
    Repair,
    RepairAll,
    RestockVehicle,
    ScientificResearch,
    SearchAndRescue,
    SellDrones,
    SellShipOnRebuy,
    SetUserShipName,
    Shipyard,
    ShipyardBuy,
    ShipyardNew,
    ShipyardSell,
    ShipyardTransfer,
    ShipyardSwap,
    StoredModules,
    StoredShips,
    TechnologyBroker,
    ClearImpound,

    // [[Powerplay]]
    PowerplayCollect,
    PowerplayDefect,
    PowerplayDeliver,
    PowerplayFastTrack,
    PowerplayJoin,
    PowerplayLeave,
    PowerplaySalary,
    PowerplayVote,
    PowerplayVoucher,

    // [[Squadrons]]
    AppliedToSquadron,
    DisbandedSquadron,
    InvitedToSquadron,
    JoinedSquadron,
    KickedFromSquadron,
    LeftSquadron,
    SharedBookmarkToSquadron,
    SquadronCreated,
    SquadronDemotion,
    SquadronPromotion,
    SquadronStartup,
    WonATrophyForSquadron,

    // [[Fleet Carriers]]
    CarrierJump,
    CarrierBuy,
    CarrierStats,
    CarrierJumpRequest,
    CarrierDecommission,
    CarrierCancelDecommission,
    CarrierBankTransfer,
    CarrierDepositFuel,
    CarrierCrewServices,
    CarrierFinance,
    CarrierShipPack,
    CarrierModulePack,
    CarrierTradeOrder,
    CarrierDockingPermission,
    CarrierNameChanged,
    CarrierJumpCancelled,

    // [[New in Odyssey]]
    Backpack,
    BackpackChange,
    BackpackMaterials,
    BookDropship,
    BookTaxi,
    BuyMicroResources,
    BuySuit,
    BuyWeapon,
    CancelDropship,
    CancelTaxi,
    CollectItems,
    CreateSuitLoadout,
    DeleteSuitLoadout,
    Disembark,
    DropItems,
    DropShipDeploy,
    Embark,
    FCMaterials,
    LoadoutEquipModule,
    LoadoutRemoveModule,
    RenameSuitLoadout,
    Resupply,
    ScanOrganic,
    SellMicroResources,
    SellOrganicData,
    SellSuit,
    SellWeapon,
    ShipLocker,
    SuitLoadout,
    SwitchSuitLoadout,
    TransferMicroResources,
    TradeMicroResources,
    UpgradeSuit,
    UpgradeWeapon,
    UseConsumable,

    // [[Other Events]]
    AfmuRepairs,
    ApproachSettlement,
    ChangeCrewRole,
    CockpitBreached,
    CommitCrime,
    Continued,
    CrewLaunchFighter,
    CrewMemberJoins,
    CrewMemberQuits,
    CrewMemberRoleChange,
    CrimeVictim,
    DatalinkScan,
    DatalinkVoucher,
    DataScanned,
    DockFighter,
    DockSRV,
    EndCrewSession,
    FighterRebuilt,
    FuelScoop,
    Friends,
    JetConeBoost,
    JetConeDamage,
    JoinACrew,
    KickCrewMember,
    LaunchDrone,
    LaunchFighter,
    LaunchSRV,
    ModuleInfo,
    Music,
    NpcCrewPaidWage,
    NpcCrewRank,
    Promotion,
    ProspectedAsteroid,
    QuitACrew,
    RebootRepair,
    ReceiveText {
        #[serde(with = "time::serde::iso8601")]
        timestamp: OffsetDateTime,
        #[serde(rename = "From")]
        from: String,
        #[serde(rename = "Message")]
        message: String,
        #[serde(rename = "Channel")]
        channel: Channel,
    },
    RepairDrone,
    ReservoirReplenished,
    Resurrect,
    Scanned,
    SelfDestruct,
    SendText {
        #[serde(with = "time::serde::iso8601")]
        timestamp: OffsetDateTime,
        #[serde(rename = "To")]
        to: String,
        #[serde(rename = "Message")]
        message: String,
    },
    Shutdown,
    Synthesis,
    SystemsShutdown,
    USSDrop,
    VehicleSwitch,
    WingAdd,
    WingInvite,
    WingJoin,
    WingLeave,
    CargoTransfer,
    SupercruiseDestinationDrop,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Channel {
    Wing,
    Local,
    VoiceChat,
    Friend,
    Player,
    Npc,
    Squadron,
    StarSystem,
}
